### ISSUE TITLE
Report Generation Invalid File Error

### ISSUE THREAD

**Issue by james-lawlor** [KCCG/mity#40]
Hi,
I ran into the following issue when attempting to run mity report 1.0.0. I was able to successfully run mity calling with 

```console
$singularity exec -B /cluster --cleanenv docker://drmjc/mity:0.3.0 mity call --normalise --reference hg38 --prefix HALB3054113 HALB3054133.bam
```
to produce `test_mity/HALB3054113.normalise.vcf.gz`

However, then running the report command:

```console
$singularity exec -B /cluster --cleanenv docker://drmjc/mity:1.0.0 mity report -k --prefix HALB3054113 --output-dir test_mity  test_mity/HALB3054113.normalise.vcf.gz
INFO:    Using cached SIF image
mity 1.0.0
Generating mity report
Traceback (most recent call last):
  File "/usr/local/bin/mity", line 33, in <module>
    main()
  File "/usr/local/bin/mity", line 29, in main
    args.func(args)
  File "/usr/local/lib/python3.10/site-packages/mitylib/commands.py", line 247, in _cmd_report
    report.Report(
  File "/usr/local/lib/python3.10/site-packages/mitylib/report.py", line 447, in __init__
    self.run()
  File "/usr/local/lib/python3.10/site-packages/mitylib/report.py", line 469, in run
    single_report = SingleReport(vcf, self.min_vaf, self.keep)
  File "/usr/local/lib/python3.10/site-packages/mitylib/report.py", line 190, in __init__
    self.run()
  File "/usr/local/lib/python3.10/site-packages/mitylib/report.py", line 196, in run
    self.vcfanno_call()
  File "/usr/local/lib/python3.10/site-packages/mitylib/report.py", line 274, in vcfanno_call
    self.annot_vcf_obj = pysam.VariantFile(annotated_file)
  File "pysam/libcbcf.pyx", line 4117, in pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4347, in pysam.libcbcf.VariantFile.open
ValueError: invalid file `b'test_mity/HALB3054113.normalise.mity.annotated.vcf'` (mode=`b'r'`) - is it VCF/BCF format?
```

Upon inspecting the outputs, `HALB3054113.normalise.mity.annotated.vcf` is an empty file, however `HALB3054113.normalise.vcf.gz` contains variants and appears to be correct. Note that HALB3054113 represents hg38-aligned illumina sequencing data from NA12878. The contents of the normalise VCF are as follows:
```
$zcat test_mity/HALB3054113.normalise.vcf.gz
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=20240309
##freebayesSource=freeBayes v1.3.5
##reference=/usr/local/lib/python3.10/site-packages/mitylib/reference/hg38.chrM.fa
##contig=<ID=chr1,length=248956422>
##contig=<ID=chr2,length=242193529>
##contig=<ID=chr3,length=198295559>
##contig=<ID=chr4,length=190214555>
##contig=<ID=chr5,length=181538259>
##contig=<ID=chr6,length=170805979>
##contig=<ID=chr7,length=159345973>
##contig=<ID=chr8,length=145138636>
##contig=<ID=chr9,length=138394717>
##contig=<ID=chr10,length=133797422>
##contig=<ID=chr11,length=135086622>
##contig=<ID=chr12,length=133275309>
##contig=<ID=chr13,length=114364328>
##contig=<ID=chr14,length=107043718>
##contig=<ID=chr15,length=101991189>
##contig=<ID=chr16,length=90338345>
##contig=<ID=chr17,length=83257441>
##contig=<ID=chr18,length=80373285>
##contig=<ID=chr19,length=58617616>
##contig=<ID=chr20,length=64444167>
##contig=<ID=chr21,length=46709983>
##contig=<ID=chr22,length=50818468>
##contig=<ID=chrX,length=156040895>
##contig=<ID=chrY,length=57227415>
##contig=<ID=chrM,length=16569>
##contig=<ID=chr1_KI270706v1_random,length=175055>
##contig=<ID=chr1_KI270707v1_random,length=32032>
##contig=<ID=chr1_KI270708v1_random,length=127682>
##contig=<ID=chr1_KI270709v1_random,length=66860>
##contig=<ID=chr1_KI270710v1_random,length=40176>
##contig=<ID=chr1_KI270711v1_random,length=42210>
##contig=<ID=chr1_KI270712v1_random,length=176043>
##contig=<ID=chr1_KI270713v1_random,length=40745>
##contig=<ID=chr1_KI270714v1_random,length=41717>
##contig=<ID=chr2_KI270715v1_random,length=161471>
##contig=<ID=chr2_KI270716v1_random,length=153799>
##contig=<ID=chr3_GL000221v1_random,length=155397>
##contig=<ID=chr4_GL000008v2_random,length=209709>
##contig=<ID=chr5_GL000208v1_random,length=92689>
##contig=<ID=chr9_KI270717v1_random,length=40062>
##contig=<ID=chr9_KI270718v1_random,length=38054>
##contig=<ID=chr9_KI270719v1_random,length=176845>
##contig=<ID=chr9_KI270720v1_random,length=39050>
##contig=<ID=chr11_KI270721v1_random,length=100316>
##contig=<ID=chr14_GL000009v2_random,length=201709>
##contig=<ID=chr14_GL000225v1_random,length=211173>
##contig=<ID=chr14_KI270722v1_random,length=194050>
##contig=<ID=chr14_GL000194v1_random,length=191469>
##contig=<ID=chr14_KI270723v1_random,length=38115>
##contig=<ID=chr14_KI270724v1_random,length=39555>
##contig=<ID=chr14_KI270725v1_random,length=172810>
##contig=<ID=chr14_KI270726v1_random,length=43739>
##contig=<ID=chr15_KI270727v1_random,length=448248>
##contig=<ID=chr16_KI270728v1_random,length=1872759>
##contig=<ID=chr17_GL000205v2_random,length=185591>
##contig=<ID=chr17_KI270729v1_random,length=280839>
##contig=<ID=chr17_KI270730v1_random,length=112551>
##contig=<ID=chr22_KI270731v1_random,length=150754>
##contig=<ID=chr22_KI270732v1_random,length=41543>
##contig=<ID=chr22_KI270733v1_random,length=179772>
##contig=<ID=chr22_KI270734v1_random,length=165050>
##contig=<ID=chr22_KI270735v1_random,length=42811>
##contig=<ID=chr22_KI270736v1_random,length=181920>
##contig=<ID=chr22_KI270737v1_random,length=103838>
##contig=<ID=chr22_KI270738v1_random,length=99375>
##contig=<ID=chr22_KI270739v1_random,length=73985>
##contig=<ID=chrY_KI270740v1_random,length=37240>
##contig=<ID=chrUn_KI270302v1,length=2274>
##contig=<ID=chrUn_KI270304v1,length=2165>
##contig=<ID=chrUn_KI270303v1,length=1942>
##contig=<ID=chrUn_KI270305v1,length=1472>
##contig=<ID=chrUn_KI270322v1,length=21476>
##contig=<ID=chrUn_KI270320v1,length=4416>
##contig=<ID=chrUn_KI270310v1,length=1201>
##contig=<ID=chrUn_KI270316v1,length=1444>
##contig=<ID=chrUn_KI270315v1,length=2276>
##contig=<ID=chrUn_KI270312v1,length=998>
##contig=<ID=chrUn_KI270311v1,length=12399>
##contig=<ID=chrUn_KI270317v1,length=37690>
##contig=<ID=chrUn_KI270412v1,length=1179>
##contig=<ID=chrUn_KI270411v1,length=2646>
##contig=<ID=chrUn_KI270414v1,length=2489>
##contig=<ID=chrUn_KI270419v1,length=1029>
##contig=<ID=chrUn_KI270418v1,length=2145>
##contig=<ID=chrUn_KI270420v1,length=2321>
##contig=<ID=chrUn_KI270424v1,length=2140>
##contig=<ID=chrUn_KI270417v1,length=2043>
##contig=<ID=chrUn_KI270422v1,length=1445>
##contig=<ID=chrUn_KI270423v1,length=981>
##contig=<ID=chrUn_KI270425v1,length=1884>
##contig=<ID=chrUn_KI270429v1,length=1361>
##contig=<ID=chrUn_KI270442v1,length=392061>
##contig=<ID=chrUn_KI270466v1,length=1233>
##contig=<ID=chrUn_KI270465v1,length=1774>
##contig=<ID=chrUn_KI270467v1,length=3920>
##contig=<ID=chrUn_KI270435v1,length=92983>
##contig=<ID=chrUn_KI270438v1,length=112505>
##contig=<ID=chrUn_KI270468v1,length=4055>
##contig=<ID=chrUn_KI270510v1,length=2415>
##contig=<ID=chrUn_KI270509v1,length=2318>
##contig=<ID=chrUn_KI270518v1,length=2186>
##contig=<ID=chrUn_KI270508v1,length=1951>
##contig=<ID=chrUn_KI270516v1,length=1300>
##contig=<ID=chrUn_KI270512v1,length=22689>
##contig=<ID=chrUn_KI270519v1,length=138126>
##contig=<ID=chrUn_KI270522v1,length=5674>
##contig=<ID=chrUn_KI270511v1,length=8127>
##contig=<ID=chrUn_KI270515v1,length=6361>
##contig=<ID=chrUn_KI270507v1,length=5353>
##contig=<ID=chrUn_KI270517v1,length=3253>
##contig=<ID=chrUn_KI270529v1,length=1899>
##contig=<ID=chrUn_KI270528v1,length=2983>
##contig=<ID=chrUn_KI270530v1,length=2168>
##contig=<ID=chrUn_KI270539v1,length=993>
##contig=<ID=chrUn_KI270538v1,length=91309>
##contig=<ID=chrUn_KI270544v1,length=1202>
##contig=<ID=chrUn_KI270548v1,length=1599>
##contig=<ID=chrUn_KI270583v1,length=1400>
##contig=<ID=chrUn_KI270587v1,length=2969>
##contig=<ID=chrUn_KI270580v1,length=1553>
##contig=<ID=chrUn_KI270581v1,length=7046>
##contig=<ID=chrUn_KI270579v1,length=31033>
##contig=<ID=chrUn_KI270589v1,length=44474>
##contig=<ID=chrUn_KI270590v1,length=4685>
##contig=<ID=chrUn_KI270584v1,length=4513>
##contig=<ID=chrUn_KI270582v1,length=6504>
##contig=<ID=chrUn_KI270588v1,length=6158>
##contig=<ID=chrUn_KI270593v1,length=3041>
##contig=<ID=chrUn_KI270591v1,length=5796>
##contig=<ID=chrUn_KI270330v1,length=1652>
##contig=<ID=chrUn_KI270329v1,length=1040>
##contig=<ID=chrUn_KI270334v1,length=1368>
##contig=<ID=chrUn_KI270333v1,length=2699>
##contig=<ID=chrUn_KI270335v1,length=1048>
##contig=<ID=chrUn_KI270338v1,length=1428>
##contig=<ID=chrUn_KI270340v1,length=1428>
##contig=<ID=chrUn_KI270336v1,length=1026>
##contig=<ID=chrUn_KI270337v1,length=1121>
##contig=<ID=chrUn_KI270363v1,length=1803>
##contig=<ID=chrUn_KI270364v1,length=2855>
##contig=<ID=chrUn_KI270362v1,length=3530>
##contig=<ID=chrUn_KI270366v1,length=8320>
##contig=<ID=chrUn_KI270378v1,length=1048>
##contig=<ID=chrUn_KI270379v1,length=1045>
##contig=<ID=chrUn_KI270389v1,length=1298>
##contig=<ID=chrUn_KI270390v1,length=2387>
##contig=<ID=chrUn_KI270387v1,length=1537>
##contig=<ID=chrUn_KI270395v1,length=1143>
##contig=<ID=chrUn_KI270396v1,length=1880>
##contig=<ID=chrUn_KI270388v1,length=1216>
##contig=<ID=chrUn_KI270394v1,length=970>
##contig=<ID=chrUn_KI270386v1,length=1788>
##contig=<ID=chrUn_KI270391v1,length=1484>
##contig=<ID=chrUn_KI270383v1,length=1750>
##contig=<ID=chrUn_KI270393v1,length=1308>
##contig=<ID=chrUn_KI270384v1,length=1658>
##contig=<ID=chrUn_KI270392v1,length=971>
##contig=<ID=chrUn_KI270381v1,length=1930>
##contig=<ID=chrUn_KI270385v1,length=990>
##contig=<ID=chrUn_KI270382v1,length=4215>
##contig=<ID=chrUn_KI270376v1,length=1136>
##contig=<ID=chrUn_KI270374v1,length=2656>
##contig=<ID=chrUn_KI270372v1,length=1650>
##contig=<ID=chrUn_KI270373v1,length=1451>
##contig=<ID=chrUn_KI270375v1,length=2378>
##contig=<ID=chrUn_KI270371v1,length=2805>
##contig=<ID=chrUn_KI270448v1,length=7992>
##contig=<ID=chrUn_KI270521v1,length=7642>
##contig=<ID=chrUn_GL000195v1,length=182896>
##contig=<ID=chrUn_GL000219v1,length=179198>
##contig=<ID=chrUn_GL000220v1,length=161802>
##contig=<ID=chrUn_GL000224v1,length=179693>
##contig=<ID=chrUn_KI270741v1,length=157432>
##contig=<ID=chrUn_GL000226v1,length=15008>
##contig=<ID=chrUn_GL000213v1,length=164239>
##contig=<ID=chrUn_KI270743v1,length=210658>
##contig=<ID=chrUn_KI270744v1,length=168472>
##contig=<ID=chrUn_KI270745v1,length=41891>
##contig=<ID=chrUn_KI270746v1,length=66486>
##contig=<ID=chrUn_KI270747v1,length=198735>
##contig=<ID=chrUn_KI270748v1,length=93321>
##contig=<ID=chrUn_KI270749v1,length=158759>
##contig=<ID=chrUn_KI270750v1,length=148850>
##contig=<ID=chrUn_KI270751v1,length=150742>
##contig=<ID=chrUn_KI270752v1,length=27745>
##contig=<ID=chrUn_KI270753v1,length=62944>
##contig=<ID=chrUn_KI270754v1,length=40191>
##contig=<ID=chrUn_KI270755v1,length=36723>
##contig=<ID=chrUn_KI270756v1,length=79590>
##contig=<ID=chrUn_KI270757v1,length=71251>
##contig=<ID=chrUn_GL000214v1,length=137718>
##contig=<ID=chrUn_KI270742v1,length=186739>
##contig=<ID=chrUn_GL000216v2,length=176608>
##contig=<ID=chrUn_GL000218v1,length=161147>
##contig=<ID=chrEBV,length=171823>
##mityCommandline="mity call --reference /usr/local/lib/python3.10/site-packages/mitylib/reference/hg38.chrM.fa --prefix HALB3054113 --min-mapping-quality 30 --min-base-quality 24 --min-alternate-fraction 0.01 --min-alternate-count 4 --out-folder-path test_mity --region chrM:1-16569 HALB3054133.bam"
##freebayesCommandline="freebayes -f /usr/local/lib/python3.10/site-packages/mitylib/reference/hg38.chrM.fa -b HALB3054133.bam --min-mapping-quality 30 --min-base-quality 24 --min-alternate-fraction 0.01 --min-alternate-count 4 --ploidy 2 --region chrM:1-16569"
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total read depth at the locus">
##INFO=<ID=DPB,Number=1,Type=Float,Description="Total read depth per bp at the locus; bases in reads overlapping / bases in haplotype">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Total number of alternate alleles in called genotypes">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated allele frequency in the range (0,1]">
##INFO=<ID=RO,Number=1,Type=Integer,Description="Count of full observations of the reference haplotype.">
##INFO=<ID=AO,Number=A,Type=Integer,Description="Count of full observations of this alternate haplotype.">
##INFO=<ID=PRO,Number=1,Type=Float,Description="Reference allele observation count, with partial observations recorded fractionally">
##INFO=<ID=PAO,Number=A,Type=Float,Description="Alternate allele observations, with partial observations recorded fractionally">
##INFO=<ID=QR,Number=1,Type=Integer,Description="Reference allele quality sum in phred">
##INFO=<ID=QA,Number=A,Type=Integer,Description="Alternate allele quality sum in phred">
##INFO=<ID=PQR,Number=1,Type=Float,Description="Reference allele quality sum in phred for partial observations">
##INFO=<ID=PQA,Number=A,Type=Float,Description="Alternate allele quality sum in phred for partial observations">
##INFO=<ID=SRF,Number=1,Type=Integer,Description="Number of reference observations on the forward strand">
##INFO=<ID=SRR,Number=1,Type=Integer,Description="Number of reference observations on the reverse strand">
##INFO=<ID=SAF,Number=A,Type=Integer,Description="Number of alternate observations on the forward strand">
##INFO=<ID=SAR,Number=A,Type=Integer,Description="Number of alternate observations on the reverse strand">
##INFO=<ID=SRP,Number=1,Type=Float,Description="Strand balance probability for the reference allele: Phred-scaled upper-bounds estimate of the probability of observing the deviation between SRF and SRR given E(SRF/SRR) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=SAP,Number=A,Type=Float,Description="Strand balance probability for the alternate allele: Phred-scaled upper-bounds estimate of the probability of observing the deviation between SAF and SAR given E(SAF/SAR) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=AB,Number=A,Type=Float,Description="Allele balance at heterozygous sites: a number between 0 and 1 representing the ratio of reads showing the reference allele to all reads, considering only reads from individuals called as heterozygous">
##INFO=<ID=ABP,Number=A,Type=Float,Description="Allele balance probability at heterozygous sites: Phred-scaled upper-bounds estimate of the probability of observing the deviation between ABR and ABA given E(ABR/ABA) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=RUN,Number=A,Type=Integer,Description="Run length: the number of consecutive repeats of the alternate allele in the reference genome">
##INFO=<ID=RPP,Number=A,Type=Float,Description="Read Placement Probability: Phred-scaled upper-bounds estimate of the probability of observing the deviation between RPL and RPR given E(RPL/RPR) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=RPPR,Number=1,Type=Float,Description="Read Placement Probability for reference observations: Phred-scaled upper-bounds estimate of the probability of observing the deviation between RPL and RPR given E(RPL/RPR) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=RPL,Number=A,Type=Float,Description="Reads Placed Left: number of reads supporting the alternate balanced to the left (5') of the alternate allele">
##INFO=<ID=RPR,Number=A,Type=Float,Description="Reads Placed Right: number of reads supporting the alternate balanced to the right (3') of the alternate allele">
##INFO=<ID=EPP,Number=A,Type=Float,Description="End Placement Probability: Phred-scaled upper-bounds estimate of the probability of observing the deviation between EL and ER given E(EL/ER) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=EPPR,Number=1,Type=Float,Description="End Placement Probability for reference observations: Phred-scaled upper-bounds estimate of the probability of observing the deviation between EL and ER given E(EL/ER) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=DPRA,Number=A,Type=Float,Description="Alternate allele depth ratio.  Ratio between depth in samples with each called alternate allele and those without.">
##INFO=<ID=ODDS,Number=1,Type=Float,Description="The log odds ratio of the best genotype combination to the second-best.">
##INFO=<ID=GTI,Number=1,Type=Integer,Description="Number of genotyping iterations required to reach convergence or bailout.">
##INFO=<ID=TYPE,Number=A,Type=String,Description="The type of allele, either snp, mnp, ins, del, or complex.">
##INFO=<ID=CIGAR,Number=A,Type=String,Description="The extended CIGAR representation of each alternate allele, with the exception that '=' is replaced by 'M' to ease VCF parsing.  Note that INDEL alleles do not have the first matched base (which is provided by default, per the spec) referred to by the CIGAR.">
##INFO=<ID=NUMALT,Number=1,Type=Integer,Description="Number of unique non-reference alleles in called genotypes at this position.">
##INFO=<ID=MEANALT,Number=A,Type=Float,Description="Mean number of unique non-reference allele observations per sample with the corresponding alternate alleles.">
##INFO=<ID=LEN,Number=A,Type=Integer,Description="allele length">
##INFO=<ID=MQM,Number=A,Type=Float,Description="Mean mapping quality of observed alternate alleles">
##INFO=<ID=MQMR,Number=1,Type=Float,Description="Mean mapping quality of observed reference alleles">
##INFO=<ID=PAIRED,Number=A,Type=Float,Description="Proportion of observed alternate alleles which are supported by properly paired read fragments">
##INFO=<ID=PAIREDR,Number=1,Type=Float,Description="Proportion of observed reference alleles which are supported by properly paired read fragments">
##INFO=<ID=MIN_DP,Number=1,Type=Integer,Description="Minimum depth in gVCF output block.">
##INFO=<ID=END,Number=1,Type=Integer,Description="Last position (inclusive) in gVCF output record.">
##INFO=<ID=technology.ILLUMINA,Number=A,Type=Float,Description="Fraction of observations supporting the alternate observed in reads from ILLUMINA">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Float,Description="Genotype Quality, the Phred-scaled marginal (or unconditional) probability of the called genotype">
##FORMAT=<ID=GL,Number=G,Type=Float,Description="Genotype Likelihood, log10-scaled likelihoods of the data given the called genotype for each possible genotype generated from the reference and alternate alleles given the sample ploidy">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Number of observation for each allele">
##FORMAT=<ID=RO,Number=1,Type=Integer,Description="Reference allele observation count">
##FORMAT=<ID=QR,Number=1,Type=Integer,Description="Sum of quality of the reference observations">
##FORMAT=<ID=AO,Number=A,Type=Integer,Description="Alternate allele observation count">
##FORMAT=<ID=QA,Number=A,Type=Integer,Description="Sum of quality of the alternate observations">
##FORMAT=<ID=MIN_DP,Number=1,Type=Integer,Description="Minimum depth in gVCF output block.">
##bcftools_normVersion=1.18 (pysam)+htslib-1.18
##bcftools_normCommand=norm -f /usr/local/lib/python3.10/site-packages/mitylib/reference/hg38.chrM.fa -m-both -o /tmp/tmp9lrwfr9q test_mity/HALB3054113.mity.call.vcf.gz; Date=Sat Mar  9 13:38:03 2024
##FILTER=<ID=FAIL,Description="Variant fails filter in at least one or all samples (depending on filter option)">
##INFO=<ID=SBR,Number=1,Type=Float,Description="For all alleles RO > 15 and (SBR > 0.9 or SBR < 0.1)">
##INFO=<ID=SBA,Number=1,Type=Float,Description="For all alleles AO > 15 and (SBA > 0.9 or SBA < 0.1)">
##FORMAT=<ID=AQA,Number=A,Type=Float,Description="Average base quality of the alternate reads, AQA=QA/AO">
##FORMAT=<ID=AQR,Number=A,Type=Float,Description="Average base quality of the reference reads, AQR=QR/RO">
##FORMAT=<ID=VAF,Number=A,Type=Float,Description="Allele frequency in the range (0,1] - the ratio of the number of alternate reads to reference reads">
##FORMAT=<ID=q,Number=A,Type=Float,Description="Phred scaled binomial probability of seeing AO reads from DP, assuming a noise floor of p=0.002.">
##FORMAT=<ID=tier,Number=A,Type=Integer,Description="Custom variant tier (TODO: change description)">
##FORMAT=<ID=POS_filter,Number=A,Type=Integer,Description="Variant falls in the blacklist of positions: MT:302-319, MT:3105-3108">
##FORMAT=<ID=SBR_filter,Number=A,Type=Integer,Description="For all alleles RO > 15 and (SBR > 0.9 or SBR < 0.1)">
##FORMAT=<ID=SBA_filter,Number=A,Type=Integer,Description="For all alleles AO > 15 and (SBA > 0.9 or SBA < 0.1)">
##FORMAT=<ID=MQMR_filter,Number=A,Type=Integer,Description="For all alleles MQMR<30">
##FORMAT=<ID=AQR_filter,Number=A,Type=Integer,Description="For all alleles AQR<20">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HALB3054133
chrM	152	.	T	C	338906	PASS	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=10323;CIGAR=1X;DP=10325;DPB=10325;DPRA=0;EPP=51.2739;EPPR=7.35324;GTI=0;LEN=1;MEANALT=1;MQM=59.9942;MQMR=60;NS=1;NUMALT=1;ODDS=14288.3;PAIRED=0.652039;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=377145;QR=74;RO=2;RPL=5027;RPP=18.2316;RPPR=7.35324;RPR=5296;RUN=1;SAF=5571;SAP=144.107;SAR=4752;SRF=2;SRP=7.35324;SRR=0;TYPE=snp;technology.ILLUMINA=1;SBR=1;SBA=0.54	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	1/1:10325:2,10323:2:74:10323:377145:-33915.6,-3101.11,0:37:0.9998:3220:36.534:1:1:1:1:1:1
chrM	263	.	A	G	273641	PASS	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=8559;CIGAR=1X;DP=8562;DPB=8562;DPRA=0;EPP=804.146;EPPR=0;GTI=0;LEN=1;MEANALT=3;MQM=59.9759;MQMR=0;NS=1;NUMALT=1;ODDS=11869.9;PAIRED=0.744947;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=306701;QR=0;RO=0;RPL=5424;RPP=1332.31;RPPR=0;RPR=3135;RUN=1;SAF=4143;SAP=21.9188;SAR=4416;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.ILLUMINA=1;SBR=0;SBA=0.484	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	1/1:8562:0,8559:0:0:8559:306701:-27587.5,-2576.52,0:0:0.9996:3220:35.834:1:1:1:1:1:1
chrM	310	.	T	CTC	115168	FAIL	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=3927;CIGAR=8M2I1X2M;DP=4529;DPB=5724;DPRA=0;EPP=148.532;EPPR=0;GTI=0;LEN=13;MEANALT=36;MQM=59.947;MQMR=0;NS=1;NUMALT=1;ODDS=3323.77;PAIRED=0.648332;PAIREDR=0;PAO=99.6667;PQA=2932.93;PQR=8618.6;PRO=287;QA=141552;QR=0;RO=0;RPL=2220;RPP=148.532;RPPR=0;RPR=1707;RUN=1;SAF=0;SAP=8530.38;SAR=3927;SRF=0;SRP=0;SRR=0;TYPE=complex;technology.ILLUMINA=1;SBR=0;SBA=0	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	1/1:4529:0,3927:0:0:3927:141552:-12731.9,-1182.14,0:0:0.8671:3220:36.046:1:0:1:0:1:1
chrM	504	.	T	A	0	FAIL	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=75;CIGAR=1X;DP=7252;DPB=7252;DPRA=0;EPP=72.5264;EPPR=2690.81;GTI=0;LEN=1;MEANALT=3;MQM=59.6133;MQMR=59.9458;NS=1;NUMALT=1;ODDS=9278.32;PAIRED=0.973333;PAIREDR=0.893778;PAO=0;PQA=0;PQR=0;PRO=0;QA=1874;QR=255056;RO=7136;RPL=65;RPP=90.593;RPPR=252.789;RPR=10;RUN=1;SAF=70;SAP=125.337;SAR=5;SRF=2463;SRP=1489.23;SRR=4673;TYPE=snp;technology.ILLUMINA=1;SBR=0.345;SBA=0.933	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	0/0:7252:7136,75:7136:255056:75:1874:0,-2002.11,-22771.6:35.7422:0.0103:293.23:24.987:1:1:1:0:1:1
chrM	507	.	T	A	1.02219e-13	FAIL	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=85;CIGAR=1X;DP=6837;DPB=6837;DPRA=0;EPP=98.0697;EPPR=2808.68;GTI=0;LEN=1;MEANALT=3;MQM=59.6588;MQMR=59.9678;NS=1;NUMALT=1;ODDS=8637.18;PAIRED=1;PAIREDR=0.899672;PAO=0;PQA=0;PQR=0;PRO=0;QA=2136;QR=232860;RO=6708;RPL=73;RPP=98.0697;RPPR=271.078;RPR=12;RUN=1;SAF=85;SAP=187.585;SAR=0;SRF=2483;SRP=985.341;SRR=4225;TYPE=snp;technology.ILLUMINA=1;SBR=0.37;SBA=1	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	0/0:6837:6708,85:6708:232860:85:2136:0,-1852.7,-20753.7:34.7138:0.0124:387.27:25.129:1:1:1:0:1:1
chrM	539	.	T	A	0	FAIL	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=175;CIGAR=1X;DP=7108;DPB=7108;DPRA=0;EPP=324.649;EPPR=3077.76;GTI=0;LEN=1;MEANALT=3;MQM=59.7029;MQMR=59.9541;NS=1;NUMALT=1;ODDS=8298.86;PAIRED=1;PAIREDR=0.942547;PAO=0;PQA=0;PQR=0;PRO=0;QA=4885;QR=240058;RO=6910;RPL=167;RPP=316.707;RPPR=1659.62;RPR=8;RUN=1;SAF=174;SAP=374.382;SAR=1;SRF=3570;SRP=19.6342;SRR=3340;TYPE=snp;technology.ILLUMINA=1;SBR=0.517;SBA=0.994	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	0/0:7108:6910,175:6910:240058:175:4885:0,-1693.58,-21153.3:34.7407:0.0246:1243.48:27.914:1:1:1:0:1:1
chrM	750	.	A	G	316796	PASS	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=9639;CIGAR=1X;DP=9641;DPB=9641;DPRA=0;EPP=96.7323;EPPR=0;GTI=0;LEN=1;MEANALT=2;MQM=59.8979;MQMR=0;NS=1;NUMALT=1;ODDS=13367.1;PAIRED=0.989729;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=352661;QR=0;RO=0;RPL=4735;RPP=9.44452;RPPR=0;RPR=4904;RUN=1;SAF=5315;SAP=224.253;SAR=4324;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.ILLUMINA=1;SBR=0;SBA=0.551	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	1/1:9641:0,9639:0:0:9639:352661:-31718.1,-2901.63,0:0:0.9998:3220:36.587:1:1:1:1:1:1
chrM	1438	.	A	G	345713	PASS	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=10551;CIGAR=1X;DP=10554;DPB=10554;DPRA=0;EPP=30.429;EPPR=0;GTI=0;LEN=1;MEANALT=3;MQM=59.6147;MQMR=0;NS=1;NUMALT=1;ODDS=14631.4;PAIRED=0.998484;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=386202;QR=0;RO=0;RPL=6289;RPP=848.617;RPPR=0;RPR=4262;RUN=1;SAF=4387;SAP=652.894;SAR=6164;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.ILLUMINA=1;SBR=0;SBA=0.416	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	1/1:10554:0,10551:0:0:10551:386202:-34730.7,-3176.17,0:0:0.9997:3220:36.603:1:1:1:1:1:1
chrM	2259	.	C	T	319969	PASS	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=9982;CIGAR=1X;DP=9994;DPB=9994;DPRA=0;EPP=151.432;EPPR=7.35324;GTI=0;LEN=1;MEANALT=3;MQM=59.9951;MQMR=60;NS=1;NUMALT=1;ODDS=13816.4;PAIRED=0.997596;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=356172;QR=74;RO=2;RPL=5326;RPP=100.663;RPPR=7.35324;RPR=4656;RUN=1;SAF=4742;SAP=56.9608;SAR=5240;SRF=0;SRP=7.35324;SRR=2;TYPE=snp;technology.ILLUMINA=1;SBR=0;SBA=0.475	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	1/1:9994:2,9982:2:74:9982:356172:-32031.4,-2998.81,0:37:0.9988:3220:35.681:1:1:1:1:1:1
chrM	3106	.	CN	C	341915	FAIL	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=10420;CIGAR=1M1D1X;DP=10464;DPB=7103.67;DPRA=0;EPP=504.971;EPPR=0;GTI=0;LEN=2;MEANALT=9;MQM=59.9949;MQMR=0;NS=1;NUMALT=1;ODDS=14449.8;PAIRED=0.998177;PAIREDR=0;PAO=256;PQA=9242;PQR=0;PRO=0;QA=380762;QR=0;RO=0;RPL=5151;RPP=5.91199;RPPR=0;RPR=5269;RUN=1;SAF=5283;SAP=7.45244;SAR=5137;SRF=0;SRP=0;SRR=0;TYPE=complex;technology.ILLUMINA=1;SBR=0;SBA=0.507	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	1/1:10464:0,10420:0:0:10420:380762:-34248.9,-3136.73,0:0:0.9958:3220:36.541:1:0:1:1:1:1
chrM	3590	.	T	A	2.59404e-13	FAIL	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=125;CIGAR=1X;DP=6027;DPB=6027;DPRA=0;EPP=29.4328;EPPR=596.925;GTI=0;LEN=1;MEANALT=3;MQM=59.728;MQMR=59.9826;NS=1;NUMALT=1;ODDS=7083.42;PAIRED=1;PAIREDR=0.996246;PAO=0;PQA=0;PQR=0;PRO=0;QA=3420;QR=208072;RO=5860;RPL=80;RPP=24.2907;RPPR=461.222;RPR=45;RUN=1;SAF=123;SAP=257.351;SAR=2;SRF=1681;SRP=2315.3;SRR=4179;TYPE=snp;technology.ILLUMINA=1;SBR=0.287;SBA=0.984	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	0/0:6027:5860,125:5860:208072:125:3420:0,-1494.08,-18408.7:35.5072:0.0207:808.12:27.36:1:1:1:0:1:1
chrM	3599	.	T	A	0	FAIL	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=80;CIGAR=1X;DP=6964;DPB=6964;DPRA=0;EPP=55.5599;EPPR=1107.77;GTI=0;LEN=1;MEANALT=3;MQM=59.9375;MQMR=59.9822;NS=1;NUMALT=1;ODDS=8787.44;PAIRED=1;PAIREDR=0.996493;PAO=0;PQA=0;PQR=0;PRO=0;QA=2144;QR=244684;RO=6844;RPL=58;RPP=38.1882;RPPR=513.143;RPR=22;RUN=1;SAF=74;SAP=128.521;SAR=6;SRF=2339;SRP=1491.55;SRR=4505;TYPE=snp;technology.ILLUMINA=1;SBR=0.342;SBA=0.925	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	0/0:6964:6844,80:6844:244684:80:2144:0,-1891.39,-21816.6:35.7516:0.0115:342.16:26.8:1:1:1:0:1:1
chrM	3605	.	T	A	0	FAIL	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=143;CIGAR=1X;DP=6937;DPB=6937;DPRA=0;EPP=83.9318;EPPR=1037.32;GTI=0;LEN=1;MEANALT=2;MQM=59.6923;MQMR=59.9767;NS=1;NUMALT=1;ODDS=8238.42;PAIRED=1;PAIREDR=0.996161;PAO=0;PQA=0;PQR=0;PRO=0;QA=3831;QR=241156;RO=6772;RPL=108;RPP=83.9318;RPPR=960.48;RPR=35;RUN=1;SAF=141;SAP=296.402;SAR=2;SRF=2568;SRP=861.241;SRR=4204;TYPE=snp;technology.ILLUMINA=1;SBR=0.379;SBA=0.986	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	0/0:6937:6772,143:6772:241156:143:3831:0,-1736.9,-21346.9:35.6107:0.0206:917.8:26.79:1:1:1:0:1:1
chrM	3611	.	T	G	0	FAIL	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=107;CIGAR=1X;DP=6791;DPB=6791;DPRA=0;EPP=156.617;EPPR=770.131;GTI=0;LEN=1;MEANALT=3;MQM=59.9813;MQMR=59.9831;NS=1;NUMALT=1;ODDS=8415.24;PAIRED=1;PAIREDR=0.996232;PAO=0;PQA=0;PQR=0;PRO=0;QA=2641;QR=235979;RO=6635;RPL=98;RPP=163.76;RPPR=1331.82;RPR=9;RUN=1;SAF=106;SAP=226.753;SAR=1;SRF=2473;SRP=936.636;SRR=4162;TYPE=snp;technology.ILLUMINA=1;SBR=0.373;SBA=0.991	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	0/0:6791:6635,107:6635:235979:107:2641:0,-1791.87,-20988.1:35.5658:0.0158:578.87:24.682:1:1:1:0:1:1
chrM	3614	.	T	A	0	FAIL	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=80;CIGAR=1X;DP=7056;DPB=7056;DPRA=0;EPP=82.1605;EPPR=771.716;GTI=0;LEN=1;MEANALT=3;MQM=59.375;MQMR=59.989;NS=1;NUMALT=2;ODDS=8929.97;PAIRED=1;PAIREDR=0.996522;PAO=0;PQA=0;PQR=0;PRO=0;QA=1995;QR=243529;RO=6901;RPL=69;RPP=94.3207;RPPR=1439.99;RPR=11;RUN=1;SAF=78;SAP=159.791;SAR=2;SRF=2812;SRP=516.136;SRR=4089;TYPE=snp;technology.ILLUMINA=1;SBR=0.407;SBA=0.975	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	0/0:7056:6901,80:6901:243529:80:1995:0,-1921.98,-21726.4:35.2889:0.0113:338.3:24.938:1:1:1:0:1:1
chrM	3614	.	T	G	0	PASS	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=71;CIGAR=1X;DP=7056;DPB=7056;DPRA=0;EPP=124.399;EPPR=771.716;GTI=0;LEN=1;MEANALT=3;MQM=59.831;MQMR=59.989;NS=1;NUMALT=2;ODDS=8929.97;PAIRED=1;PAIREDR=0.996522;PAO=0;PQA=0;PQR=0;PRO=0;QA=1742;QR=243529;RO=6901;RPL=61;RPP=82.5596;RPPR=1439.99;RPR=10;RUN=1;SAF=63;SAP=95.5273;SAR=8;SRF=2812;SRP=516.136;SRR=4089;TYPE=snp;technology.ILLUMINA=1;SBR=0.407;SBA=0.887	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	0/0:7056:6901,71:6901:243529:71:1742:0,-1942.01,-21749.2:35.2889:0.0101:271.55:24.535:1:1:1:1:1:1
chrM	4745	.	A	G	181846	PASS	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=5867;CIGAR=1X;DP=5869;DPB=5869;DPRA=0;EPP=923.463;EPPR=0;GTI=0;LEN=1;MEANALT=3;MQM=42.5352;MQMR=0;NS=1;NUMALT=1;ODDS=8137.99;PAIRED=0.99983;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=212164;QR=0;RO=0;RPL=2620;RPP=148.514;RPPR=0;RPR=3247;RUN=1;SAF=3924;SAP=1455.48;SAR=1943;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.ILLUMINA=1;SBR=0;SBA=0.669	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	1/1:5869:0,5867:0:0:5867:212164:-18446.4,-1766.14,0:0:0.9997:3220:36.162:1:1:1:1:1:1
chrM	4769	.	A	G	177804	PASS	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=5772;CIGAR=1X;DP=5776;DPB=5776;DPRA=0;EPP=226.064;EPPR=3.73412;GTI=0;LEN=1;MEANALT=2;MQM=42.545;MQMR=57;NS=1;NUMALT=1;ODDS=7967.14;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=209146;QR=111;RO=3;RPL=2531;RPP=192.657;RPPR=9.52472;RPR=3241;RUN=1;SAF=4254;SAP=2819.19;SAR=1518;SRF=1;SRP=3.73412;SRR=2;TYPE=snp;technology.ILLUMINA=1;SBR=0.333;SBA=0.737	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	1/1:5776:3,5772:3:111:5772:209146:-18119.1,-1728.39,0:37:0.9993:3220:36.235:1:1:1:1:1:1
chrM	7337	.	G	A	332168	PASS	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=10409;CIGAR=1X;DP=10412;DPB=10412;DPRA=0;EPP=3.12066;EPPR=5.18177;GTI=0;LEN=1;MEANALT=2;MQM=53.5568;MQMR=60;NS=1;NUMALT=1;ODDS=14421;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=376668;QR=37;RO=1;RPL=7251;RPP=3497.86;RPPR=5.18177;RPR=3158;RUN=1;SAF=5417;SAP=40.6914;SAR=4992;SRF=0;SRP=5.18177;SRR=1;TYPE=snp;technology.ILLUMINA=1;SBR=0;SBA=0.52	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	1/1:10412:1,10409:1:37:10409:376668:-33585.1,-3130.35,0:37:0.9997:3220:36.187:1:1:1:1:1:1
chrM	8860	.	A	G	178151	PASS	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=5800;CIGAR=1X;DP=5801;DPB=5801;DPRA=0;EPP=386.441;EPPR=0;GTI=0;LEN=1;MEANALT=2;MQM=39.9276;MQMR=0;NS=1;NUMALT=1;ODDS=8045.11;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=208995;QR=0;RO=0;RPL=2348;RPP=459.325;RPPR=0;RPR=3452;RUN=1;SAF=2600;SAP=137.791;SAR=3200;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.ILLUMINA=1;SBR=0;SBA=0.448	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	1/1:5801:0,5800:0:0:5800:208995:-17919,-1745.97,0:0:0.9998:3220:36.034:1:1:1:1:1:1
chrM	13326	.	T	C	360387	PASS	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=10960;CIGAR=1X;DP=10962;DPB=10962;DPRA=0;EPP=47.1498;EPPR=3.0103;GTI=0;LEN=1;MEANALT=1;MQM=59.9108;MQMR=60;NS=1;NUMALT=1;ODDS=15172.5;PAIRED=0.996624;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=400902;QR=62;RO=2;RPL=5391;RPP=9.28776;RPPR=7.35324;RPR=5569;RUN=1;SAF=5547;SAP=6.56787;SAR=5413;SRF=1;SRP=3.0103;SRR=1;TYPE=snp;technology.ILLUMINA=1;SBR=0.5;SBA=0.506	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	1/1:10962:2,10960:2:62:10960:400902:-36049.3,-3294,0:31:0.9998:3220:36.579:1:1:1:1:1:1
chrM	13680	.	C	T	293920	PASS	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=9268;CIGAR=1X;DP=9286;DPB=9286;DPRA=0;EPP=4.3636;EPPR=9.04217;GTI=0;LEN=1;MEANALT=3;MQM=59.9914;MQMR=60;NS=1;NUMALT=1;ODDS=12737.5;PAIRED=0.993742;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=327176;QR=333;RO=9;RPL=4800;RPP=28.8355;RPPR=14.8328;RPR=4468;RUN=1;SAF=4828;SAP=38.2824;SAR=4440;SRF=8;SRP=14.8328;SRR=1;TYPE=snp;technology.ILLUMINA=1;SBR=0.889;SBA=0.521	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	1/1:9286:9,9268:9:333:9268:327176:-29399.8,-2762.65,0:37:0.9981:3220:35.302:1:1:1:1:1:1
chrM	13762	.	T	G	0	FAIL	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=113;CIGAR=1X;DP=6078;DPB=6078;DPRA=0;EPP=129.09;EPPR=352.689;GTI=0;LEN=1;MEANALT=2;MQM=59.9735;MQMR=59.9936;NS=1;NUMALT=1;ODDS=7327.19;PAIRED=1;PAIREDR=0.99715;PAO=0;PQA=0;PQR=0;PRO=0;QA=3239;QR=210780;RO=5964;RPL=95;RPP=116.945;RPPR=4.40989;RPR=18;RUN=1;SAF=109;SAP=214.873;SAR=4;SRF=1335;SRP=3953.62;SRR=4629;TYPE=snp;technology.ILLUMINA=1;SBR=0.224;SBA=0.965	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	0/0:6078:5964,113:5964:210780:113:3239:0,-1537.88,-18668.5:35.3421:0.0186:683.4:28.664:1:1:1:0:1:1
chrM	13768	.	T	G	0	FAIL	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=119;CIGAR=1X;DP=6051;DPB=6051;DPRA=0;EPP=122.733;EPPR=551.989;GTI=0;LEN=1;MEANALT=3;MQM=60;MQMR=59.9933;NS=1;NUMALT=1;ODDS=7263.06;PAIRED=1;PAIREDR=0.996625;PAO=0;PQA=0;PQR=0;PRO=0;QA=3182;QR=208054;RO=5926;RPL=96;RPP=100.252;RPPR=6.24809;RPR=23;RUN=1;SAF=113;SAP=211.928;SAR=6;SRF=1441;SRP=3398.34;SRR=4485;TYPE=snp;technology.ILLUMINA=1;SBR=0.243;SBA=0.95	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	0/0:6051:5926,119:5926:208054:119:3182:0,-1533.41,-18428.6:35.1087:0.0197:745.1:26.739:1:1:1:0:1:1
chrM	13769	.	T	G	7.85929e-14	FAIL	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=93;CIGAR=1X;DP=6350;DPB=6350;DPRA=0;EPP=114.176;EPPR=549.358;GTI=0;LEN=1;MEANALT=3;MQM=60;MQMR=59.9901;NS=1;NUMALT=1;ODDS=7926.32;PAIRED=1;PAIREDR=0.99632;PAO=0;PQA=0;PQR=0;PRO=0;QA=2449;QR=222706;RO=6250;RPL=81;RPP=114.176;RPPR=28.3384;RPR=12;RUN=1;SAF=91;SAP=187.959;SAR=2;SRF=1630;SRP=3109.12;SRR=4620;TYPE=snp;technology.ILLUMINA=1;SBR=0.261;SBA=0.978	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	0/0:6350:6250,93:6250:222706:93:2449:0,-1689.06,-19812.2:35.633:0.0146:479.57:26.333:1:1:1:0:1:1
chrM	13787	.	T	G	0	FAIL	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=80;CIGAR=1X;DP=6815;DPB=6815;DPRA=0;EPP=107.35;EPPR=1576.51;GTI=0;LEN=1;MEANALT=3;MQM=60;MQMR=59.9886;NS=1;NUMALT=1;ODDS=8678.72;PAIRED=1;PAIREDR=0.995838;PAO=0;PQA=0;PQR=0;PRO=0;QA=2152;QR=240908;RO=6728;RPL=71;RPP=107.35;RPPR=3.47635;RPR=9;RUN=1;SAF=80;SAP=176.728;SAR=0;SRF=1797;SRP=3173.06;SRR=4931;TYPE=snp;technology.ILLUMINA=1;SBR=0.267;SBA=1	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	0/0:6815:6728,80:6728:240908:80:2152:0,-1855.78,-21476.1:35.8068:0.0117:348.53:26.9:1:1:1:0:1:1
chrM	14831	.	G	A	318204	PASS	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=9831;CIGAR=1X;DP=9876;DPB=9876;DPRA=0;EPP=10.9004;EPPR=3.9246;GTI=0;LEN=1;MEANALT=2;MQM=59.9868;MQMR=54.8947;NS=1;NUMALT=1;ODDS=13175.4;PAIRED=0.996033;PAIREDR=0.263158;PAO=0;PQA=0;PQR=0;PRO=0;QA=355231;QR=1370;RO=38;RPL=4765;RPP=23.0223;RPPR=47.8112;RPR=5066;RUN=1;SAF=5231;SAP=90.9561;SAR=4600;SRF=18;SRP=3.23888;SRR=20;TYPE=snp;technology.ILLUMINA=1;SBR=0.474;SBA=0.532	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	1/1:9876:38,9831:38:1370:9831:355231:-31830.6,-2848.56,0:36.0526:0.9954:3220:36.134:1:1:1:1:1:1
chrM	14872	.	C	T	316183	PASS	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=9754;CIGAR=1X;DP=9818;DPB=9818;DPRA=0;EPP=269.454;EPPR=3.58936;GTI=0;LEN=1;MEANALT=3;MQM=59.9872;MQMR=55.0167;NS=1;NUMALT=1;ODDS=12805;PAIRED=0.996514;PAIREDR=0.2;PAO=0;PQA=0;PQR=0;PRO=0;QA=354051;QR=2196;RO=60;RPL=4702;RPP=30.2817;RPPR=14.7363;RPR=5052;RUN=1;SAF=4834;SAP=4.65683;SAR=4920;SRF=31;SRP=3.15506;SRR=29;TYPE=snp;technology.ILLUMINA=1;SBR=0.517;SBA=0.496	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	1/1:9818:60,9754:60:2196:9754:354051:-31650,-2758.12,0:36.6:0.9935:3220:36.298:1:1:1:1:1:1
chrM	14918	.	G	A	9.4697e-13	PASS	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=304;CIGAR=1X;DP=10364;DPB=10364;DPRA=0;EPP=3.03887;EPPR=3.68735;GTI=0;LEN=1;MEANALT=3;MQM=60;MQMR=59.9555;NS=1;NUMALT=1;ODDS=10749.7;PAIRED=0.993421;PAIREDR=0.992842;PAO=0;PQA=0;PQR=0;PRO=0;QA=10965;QR=367202;RO=10058;RPL=147;RPP=3.7246;RPPR=342.509;RPR=157;RUN=1;SAF=192;SAP=48.7255;SAR=112;SRF=5507;SRP=200.325;SRR=4551;TYPE=snp;technology.ILLUMINA=1;SBR=0.548;SBA=0.632	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	0/0:10364:10058,304:10058:367202:304:10965:0,-2132.88,-32039.6:36.5084:0.0293:2360.21:36.069:1:1:1:1:1:1
chrM	15326	.	A	G	352312	PASS	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=10730;CIGAR=1X;DP=10731;DPB=10731;DPRA=0;EPP=25.5863;EPPR=0;GTI=0;LEN=1;MEANALT=2;MQM=59.9976;MQMR=0;NS=1;NUMALT=1;ODDS=14879.5;PAIRED=0.995993;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=391873;QR=0;RO=0;RPL=5436;RPP=7.09097;RPPR=0;RPR=5294;RUN=1;SAF=5682;SAP=84.3557;SAR=5048;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.ILLUMINA=1;SBR=0;SBA=0.53	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	1/1:10731:0,10730:0:0:10730:391873:-35248.4,-3230.05,0:0:0.9999:3220:36.521:1:1:1:1:1:1
chrM	16023	.	G	A	213224	PASS	AB=0.640247;ABP=2078.77;AC=1;AF=0.5;AN=2;AO=7779;CIGAR=1X;DP=12150;DPB=12150;DPRA=0;EPP=10.983;EPPR=29.5803;GTI=0;LEN=1;MEANALT=3;MQM=59.982;MQMR=59.9931;NS=1;NUMALT=1;ODDS=24099.3;PAIRED=0.97339;PAIREDR=0.972713;PAO=0;PQA=0;PQR=0;PRO=0;QA=280886;QR=159641;RO=4361;RPL=4083;RPP=44.8176;RPPR=20.052;RPR=3696;RUN=1;SAF=3154;SAP=607.037;SAR=4625;SRF=1928;SRP=129.995;SRR=2433;TYPE=snp;technology.ILLUMINA=1;SBR=0.442;SBA=0.405	GT:DP:AD:RO:QR:AO:QA:GL:AQR:VAF:q:AQA:tier:POS_filter:SBR_filter:SBA_filter:MQMR_filter:AQR_filter	0/1:12150:4361,7779:4361:159641:7779:280886:-21610.2,0,-10705:36.6065:0.6402:3220:36.108:1:1:1:1:1:1
```

I have successfully run this sample using mity 0.3.0, so I do not believe it to be an issue with the underlying BAM data or with my local environment or singularity setup.

**Comment by drmjc** [comment]
Thanks for the solid bug report James. 
`vcfanno` creates that file a few lines earlier (which we only introduced in v1.0.0): https://github.com/KCCG/mity/blob/master/mitylib/report.py#L256-L271, so my first thought is whether vcfanno is working within your singularity environment. Can you please post any logs you see from that command?
thanks

**Comment by james-lawlor** [comment]
vcfanno does not seem to be working within my singularity environment

```console
$ singularity exec -B /cluster docker://drmjc/mity:1.0.0 vcfanno
INFO:    Using cached SIF image
FATAL:   "vcfanno": executable file not found in $PATH
$ singularity exec -B /cluster docker://drmjc/mity:1.0.0 bash
INFO:    Using cached SIF image
$ Singularity> echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by christianfares** [comment]
HI @james-lawlor we've updated mity to install vcfanno in the Dockerfile which should resolve the issue you are having. Can you please try again with version 1.1.0?

**Comment by james-lawlor** [comment]
@christianfares That resolved the issue, everything works as expected now. Thank you!

**Comment by DarioS** [comment]
This still happens for the `pipx` installation mode. Putting `vcfanno` in a `PATH` folder works.
